# Site settings 
title: Srikar Katta
email: srikar.katta@duke.edu
description: > # this means to ignore newlines until "baseurl:"
  PhD in Computer Science
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kattasa.github.io" # the base hostname & protocol for your site
# google_scholar_id: XKCyZk0AAAAJ&hl
# arxiv_url:  "https://arxiv.org/a/airoldi_e_1"
# github_username:  airoldi
# twitter_username:  eairoldi
# orchid_id:  0000-0002-3512-0542

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
jobtitle: "Almost Matching Exactly Lab\
           Duke University"
excerpt_separator: "<!--more-->"

# SEO stuff 
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
